name: fcbtest
version: 0.1
summary: fcbtes–µ is Rally + Tempest + refstack tests
description: |
  Snap for running tests for Openstack platform using Rally framework, Tempest verifier and tests from refstack.

grade: devel
confinement: classic

environment:
  PATH: $PATH:$SNAP/bin:$SNAP/bin/testrepository-0.0.20/:$SNAP/usr/bin
  PYTHONPATH: $SNAP/lib/python2.7/site-packages:$SNAP/bin/rally

apps:
  fcbtest:
    command: echo "Usage - 0) SOURCE YOUR NOVARC 1)fcbtest.rallyinit 2) fcbtest.rally verify start 3) fcbtest.rallymanage for other settings"
    plugs: [home, network, network-bind]
  rally:
    command: rally
    plugs: [home, network, network-bind]
    aliases:
     - rally
  rallymanage:
    command: rally-manage
    plugs: [home, network, network-bind]
    aliases:
      - rallymanage
  rallyinit:
    command: bin/rallyinit.sh
    plugs: [home, network, network-bind] 
    aliases:
      - rallyinit
  tempestinit:
    command: rally verify install --source /snap/fcbtest/current/tempest
    plugs: [home, network, network-bind]

parts:
  rally:
    plugin: python
    python-version: python2
    stage-packages: [python-pip, build-essential, libffi-dev, libpq-dev, libssl-dev, libxml2-dev, libxslt1-dev, python-dev, iputils-ping, libdb5.3, zlib1g, libcomerr2, libgcc1, python-testrepository]
    build-packages: [python-pip, build-essential, libffi-dev, libpq-dev, libssl-dev, libxml2-dev, libxslt1-dev, python-dev, iputils-ping, zlib1g, libcomerr2, libgcc1, python-testrepository]
    source: http://tarballs.openstack.org/rally/rally-0.7.0.tar.gz
    python-packages:
      - 'argparse'
      - 'tox<=1.6.1' 
      - 'alembic==0.9.7'
      - 'ansible==2.4.3.0'
      - 'appdirs==1.4.3'
      - 'asn1crypto==0.24.0'
      - 'Babel==2.5.3'
      - 'bcrypt==3.1.4'
      - 'boto==2.48.0'
      - 'certifi==2018.1.18'
      - 'cffi==1.11.4'
      - 'chardet==3.0.4'
      - 'click==6.7'
      - 'cliff==2.11.0'
      - 'cmd2==0.8.0'
      - 'contextlib2==0.5.5'
      - 'cryptography==2.1.4'
      - 'debtcollector==1.19.0'
      - 'decorator==4.3.0'
      - 'deprecation==1.1'
      - 'dogpile.cache==0.6.4'
      - 'enum34==1.1.6'
      - 'extras'
      - 'fasteners==0.14.1'
      - 'fixtures==3.0.0'
      - 'funcsigs==1.0.2'
      - 'functools32==3.2.3.post2'
      - 'futures==3.2.0'
      - 'futurist==1.6.0'
      - 'gnocchiclient==7.0.1'
      - 'httplib2==0.10.3'
      - 'idna==2.6'
      - 'ipaddress==1.0.19'
      - 'iso8601==0.1.12'
      - 'Jinja2==2.10'
      - 'jmespath==0.9.3'
      - 'jsonpatch==1.21'
      - 'jsonpointer==2.0'
      - 'jsonschema==2.6.0'
      - 'keystoneauth1==3.4.0'
      - 'kubernetes==4.0.0'
      - 'linecache2==1.0.0'
      - 'Mako==1.0.7'
      - 'MarkupSafe==1.0'
      - 'monotonic==1.4'
      - 'morph==0.1.2'
      - 'msgpack==0.5.4'
      - 'munch==2.2.0'
      - 'murano-pkg-check==0.3.0'
      - 'netaddr==0.7.19'
      - 'netifaces==0.10.6'
      - 'oauth2client==4.1.2'
      - 'openstacksdk==0.11.3'
      - 'os-client-config==1.29.0'
      - 'os-faults==0.1.17'
      - 'os-service-types==1.1.0'
      - 'osc-lib==1.9.0'
      - 'oslo.concurrency==3.25.0'
      - 'oslo.config==6.4.0'
      - 'oslo.context==2.20.0'
      - 'oslo.db==4.40.0'
      - 'oslo.i18n==3.19.0'
      - 'oslo.log==3.39.0'
      - 'oslo.serialization==2.24.0'
      - 'oslo.utils==3.35.0'
      - 'osprofiler==1.15.1'
      - 'packaging==16.8'
      - 'paramiko==2.4.1'
      - 'pbr==4.1.1'
      - 'ply==3.10'
      - 'positional==1.2.1'
      - 'PrettyTable==0.7.1'
      - 'pyasn1==0.4.2'
      - 'pyasn1-modules==0.2.1'
      - 'pycparser==2.18'
      - 'pycrypto==2.6.1'
      - 'pyghmi==1.0.38'
      - 'pyinotify==0.9.6'
      - 'PyNaCl==1.2.1'
      - 'pyOpenSSL==18.0.0'
      - 'pyparsing==2.2.0'
      - 'pyperclip==1.6.0'
      - 'pytest==3.3.0'
      - 'pytest-cov==2.5.1'
      - 'pytest-forked==0.2'
      - 'pytest-html==1.16.0'
      - 'pytest-metadata==1.5.1'
      - 'pytest-xdist==1.20.1'
      - 'python-ceilometerclient==2.9.0'
      - 'python-cinderclient==3.5.0'
      - 'python-dateutil==2.6.1'
      - 'python-designateclient==2.9.0'
      - 'python-editor==1.0.3'
      - 'python-glanceclient==2.9.1'
      - 'python-heatclient==1.14.0'
      - 'python-ironicclient==2.2.0'
      - 'python-keystoneclient==3.15.0'
      - 'python-magnumclient==2.8.0'
      - 'python-manilaclient==1.21.0'
      - 'python-mimeparse==1.6.0'
      - 'python-mistralclient==3.2.0'
      - 'python-monascaclient==1.10.0'
      - 'python-muranoclient==1.0.1'
      - 'python-neutronclient==6.7.0'
      - 'python-novaclient==9.1.1'
      - 'python-openstackclient==3.14.0'
      - 'python-saharaclient==1.5.0'
      - 'python-senlinclient==1.7.0'
      - 'python-subunit==1.3.0'
      - 'python-swiftclient==3.5.0'
      - 'python-troveclient==2.14.0'
      - 'python-watcherclient==1.6.0'
      - 'python-zaqarclient==1.9.0'
      - 'pytz==2018.3'
      - 'PyYAML==3.13'
      - 'requests==2.19.1'
      - 'requestsexceptions==1.4.0'
      - 'rfc3986==1.1.0'
      - 'rsa==3.4.2'
      - 'semantic-version==2.6.0'
      - 'simplejson==3.13.2'
      - 'six==1.11.0'
      - 'SQLAlchemy==1.2.10'
      - 'sqlalchemy-migrate==0.11.0'
      - 'sqlparse==0.2.4'
      - 'stevedore==1.28.0'
      - 'subprocess32==3.2.7'
      - 'Tempita==0.5.2'
      - 'testtools==2.3.0'
      - 'traceback2==1.4.0'
      - 'ujson==1.35'
      - 'unicodecsv==0.14.1'
      - 'unittest2==1.1.0'
      - 'urllib3==1.22'
      - 'virtualenv==16.0.0'
      - 'warlock==1.2.0'
      - 'WebOb==1.7.4'
      - 'websocket-client==0.40.0'
      - 'wrapt==1.10.11'
      - 'yaql==1.1.3'
  download-tempest:
    after: [rally]
    plugin: python
    python-version: python2
    python-packages: [testtools, extras]
  copy-parts:
    after: [download-tempest]
    plugin: copy
    files:
      tempest/: tempest/
      testrepository-0.0.20/: bin/testrepository-0.0.20/
      extras-1.0.0-py2.py3-none-any.whl: extras-1.0.0-py2.py3-none-any.whl
      testtools-2.3.0-py2.py3-none-any.whl: testtools-2.3.0-py2.py3-none-any.whl
      rallyinit.sh: bin/rallyinit.sh
